INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (1, 'เสื้อยืด1', 150.00, 'man', 'plain color', 'xs', 20);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (2, 'เสื้อยืด2', 200.00, 'woman', 'pattern', 's', 10);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (3, 'เสื้อยืด3', 250.00, 'man', 'figure', 'm', 50);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (4, 'เสื้อยืด4', 300.00, 'woman', 'plain color', 'l', 60);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (5, 'เสื้อยืด5', 350.00, 'man', 'pattern', 'xl', 75);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (6, 'เสื้อยืด6', 400.00, 'woman', 'figure', 'xs', 91);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (7, 'เสื้อยืด7', 450.00, 'man', 'plain color', 's', 107);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (8, 'เสื้อยืด8', 500.00, 'woman', 'pattern', 'm', 123);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (9, 'เสื้อยืด9', 550.00, 'man', 'figure', 'l', 139);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (10, 'เสื้อยืด10', 600.00, 'woman', 'plain color', 'xl', 155);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (11, 'เสื้อยืด11', 650.00, 'man', 'pattern', 'xs', 171);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (12, 'เสื้อยืด12', 700.00, 'woman', 'figure', 's', 187);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (13, 'เสื้อยืด13', 750.00, 'man', 'plain color', 'm', 203);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (14, 'เสื้อยืด14', 800.00, 'woman', 'pattern', 'l', 219);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (15, 'เสื้อยืด15', 850.00, 'man', 'figure', 'xl', 235);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (16, 'เสื้อยืด16', 900.00, 'woman', 'plain color', 'xs', 251);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (17, 'เสื้อยืด17', 950.00, 'man', 'pattern', 's', 267);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (18, 'เสื้อยืด18', 1000.00, 'woman', 'figure', 'm', 283);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (19, 'เสื้อยืด19', 1050.00, 'man', 'plain color', 'l', 299);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (20, 'เสื้อยืด20', 1100.00, 'woman', 'pattern', 'xl', 315);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (21, 'เสื้อยืด21', 1150.00, 'man', 'figure', 'xs', 331);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (22, 'เสื้อยืด22', 1200.00, 'woman', 'plain color', 's', 347);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (23, 'เสื้อยืด23', 1250.00, 'man', 'pattern', 'm', 363);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (24, 'เสื้อยืด24', 1300.00, 'woman', 'figure', 'l', 379);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (25, 'เสื้อยืด25', 1350.00, 'man', 'plain color', 'xl', 395);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (26, 'เสื้อยืด26', 1400.00, 'woman', 'pattern', 'xs', 411);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (27, 'เสื้อยืด27', 1450.00, 'man', 'figure', 's', 427);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (28, 'เสื้อยืด28', 1500.00, 'woman', 'plain color', 'm', 443);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (29, 'เสื้อยืด29', 1550.00, 'man', 'pattern', 'l', 459);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (30, 'เสื้อยืด30', 1600.00, 'woman', 'figure', 'xl', 475);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (31, 'เสื้อยืด31', 1650.00, 'man', 'plain color', 'xs', 491);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (32, 'เสื้อยืด32', 1700.00, 'woman', 'pattern', 's', 507);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (33, 'เสื้อยืด33', 1750.00, 'man', 'figure', 'm', 523);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (34, 'เสื้อยืด34', 1800.00, 'woman', 'plain color', 'l', 539);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (35, 'เสื้อยืด35', 1850.00, 'man', 'pattern', 'xl', 555);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (36, 'เสื้อยืด36', 1900.00, 'woman', 'figure', 'xs', 571);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (37, 'เสื้อยืด37', 1950.00, 'man', 'plain color', 's', 587);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (38, 'เสื้อยืด38', 2000.00, 'woman', 'pattern', 'm', 603);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (39, 'เสื้อยืด39', 2050.00, 'man', 'figure', 'l', 619);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (40, 'เสื้อยืด40', 2100.00, 'woman', 'plain color', 'xl', 635);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (41, 'เสื้อยืด41', 2150.00, 'man', 'pattern', 'xs', 651);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (42, 'เสื้อยืด42', 2200.00, 'woman', 'figure', 's', 667);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (43, 'เสื้อยืด43', 2250.00, 'man', 'plain color', 'm', 683);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (44, 'เสื้อยืด44', 2300.00, 'woman', 'pattern', 'l', 699);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (45, 'เสื้อยืด45', 2350.00, 'man', 'figure', 'xl', 715);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (46, 'เสื้อยืด46', 2400.00, 'woman', 'plain color', 'xs', 731);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (47, 'เสื้อยืด47', 2450.00, 'man', 'pattern', 's', 747);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (48, 'เสื้อยืด48', 2500.00, 'woman', 'figure', 'm', 763);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (49, 'เสื้อยืด49', 2550.00, 'man', 'plain color', 'l', 779);
INSERT INTO `product`(`Id`, `ProductName`, `ProductPrice`, `Gender`, `Category`, `Size`, `NumCount`) VALUES (50, 'เสื้อยืด50', 2600.00, 'woman', 'pattern', 'xl', 795);
